"""Conversation application package.

This package owns Conversation-specific semantics and execution adapters.
sudofx remains the authority substrate; importing this package grants no power.
"""

from .application import (
    APPLICATION_ID,
    APPLICATION_VERSION,
    CONVERSATION_APPLICATION,
    DEFAULT_CONTEXT_TURNS,
    MAX_DURABLE_OBSERVATIONS,
    MAX_MESSAGE_CHARS,
    MAX_OBSERVATION_CHARS,
    MAX_OBSERVATIONS_PER_TURN,
    assistant_message,
    bounded_context,
    conversation_web_tools,
    declared_commitment_updates,
    enforce_response_commitments,
    grounded_commitment_updates,
    human_message,
    matrix_campaign_projection,
    record_matrix_result,
    private_assistant_descriptor,
    private_assistant_message,
    private_bounded_context,
    private_human_message,
    private_message_descriptor,
    public_urls,
    start_matrix_campaign,
    stop_matrix_campaign,
    validate_private_message,
)

__all__ = [
    "APPLICATION_ID",
    "APPLICATION_VERSION",
    "CONVERSATION_APPLICATION",
    "DEFAULT_CONTEXT_TURNS",
    "MAX_DURABLE_OBSERVATIONS",
    "MAX_MESSAGE_CHARS",
    "MAX_OBSERVATION_CHARS",
    "MAX_OBSERVATIONS_PER_TURN",
    "assistant_message",
    "bounded_context",
    "conversation_web_tools",
    "declared_commitment_updates",
    "enforce_response_commitments",
    "grounded_commitment_updates",
    "human_message",
    "matrix_campaign_projection",
    "record_matrix_result",
    "private_assistant_descriptor",
    "private_assistant_message",
    "private_bounded_context",
    "private_human_message",
    "private_message_descriptor",
    "public_urls",
    "start_matrix_campaign",
    "stop_matrix_campaign",
    "validate_private_message",
]
